### ISSUE TITLE
Settings is not applied

### ISSUE THREAD

**Issue by PSF1** [jcraane/gpt-mentor-plugin#10] opened 2023-03-29 11:02 UTC
I have these prompts set:

![imagen](https://user-images.githubusercontent.com/10193279/228513556-69fac0d0-5db1-4d79-b175-0f07a0592fb4.png)

But, when I send an ask, the plunging sends the default prompt:

![imagen](https://user-images.githubusercontent.com/10193279/228513806-c54a7766-69a2-4ffd-9c06-425300ec1976.png)

**Comment by jcraane** [comment] 2023-03-29 11:53
Thanks for reporting! I am going to look into this.

**Comment by jcraane** [comment] 2023-03-29 14:07
This is fixed in the upcoming release, 0.0.6

**Comment by jcraane** [comment] 2023-03-29 14:18
Version 0.0.6 is uploaded, will be available within 1 day I think. If the issue is still present in 0.0.6, please let me know.

**Closed by jcraane** 2023-03-29 14:18 UTC
